### ISSUE TITLE
E/MethodChannel#image_viewer(12152): java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.

### ISSUE THREAD

**Issue by adnankhan74444** [TahaMalas/flutter_image_viewer#5] opened 2021-02-14 07:36 UTC
Facing this error in android.

**Comment by TahaMalas** [comment] 2021-02-14 08:08
Duplicate of #3 

Please review it if the issue is still present kindly re-open the issue.

**Closed by TahaMalas** 2021-02-14 08:08 UTC
